//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetFinancialsVTDIApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BudgetFinancialsDBEntities : DbContext
    {
        public BudgetFinancialsDBEntities()
            : base("name=BudgetFinancialsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserDebtTb> UserDebtTbs { get; set; }
        public virtual DbSet<UserSavingsTb> UserSavingsTbs { get; set; }
        public virtual DbSet<UsersTb> UsersTbs { get; set; }
    }
}
