//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetFinancialsVTDIApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSavingsTb
    {
        public int SavingsID { get; set; }
        public int UserID { get; set; }
        public int StartingSavings { get; set; }
        public int SavingsGoal { get; set; }
        public string SavingsName { get; set; }
        public Nullable<int> AddtoSavings { get; set; }
        public int SavingsInterestRate { get; set; }
        public Nullable<System.DateTime> DateSavingsUpdate { get; set; }
        public Nullable<decimal> CurrentSavings { get; set; }
    
        public virtual UsersTb UsersTb { get; set; }
    }
}
