//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetFinancialsVTDIApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDebtTb
    {
        public int DebtID { get; set; }
        public int UserID { get; set; }
        public string DebtName { get; set; }
        public Nullable<int> DebtInterestRate { get; set; }
        public string DebtType { get; set; }
        public Nullable<System.DateTime> DateDebtUpdate { get; set; }
        public Nullable<int> MonthlyPayment { get; set; }
        public Nullable<decimal> CurrentDebt { get; set; }
    
        public virtual UsersTb UsersTb { get; set; }
    }
}
